src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 * @ORM\Table
 */
class Task
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private \Datetime $createdAt;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Vous devez saisir un titre.")
     */
    private string $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Vous devez saisir du contenu.")
     */
    private string $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isDone;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tasks")
     */
    private $User;

    public function __construct()
    {
        $this->createdAt = new \Datetime();
        $this->isDone = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): \Datetime
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function setContent($content): self
    {
        $this->content = $content;
        return $this;
    }

    public function getIsDone(): bool
    {
        return $this->isDone;
    }

    public function setIsDone(bool $isDone): self
    {
        $this->isDone = $isDone;
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextareaType::class, [
                'label' => 'Titre'
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Contenu'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Entity\Task;
use App\Form\SearchType;
use App\Form\TaskType;
use App\Service\ToggleTaskService;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TaskController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/tasks", name="task_list")
     */
    public function list(ManagerRegistry $doctrine, Request $request): Response
    {
        $data = new SearchData();
        $form = $this->createForm(SearchType::class, $data);
        $form->handleRequest($request);
        $tasks = $doctrine->getRepository(Task::class)->findSearch($data);
        return $this->render('task/list.html.twig', [
            'tasks' => $tasks,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/tasks/list/done", name="task_done_list")
     */
    public function listTaskDone(ManagerRegistry $doctrine): Response
    {
        return $this->render('task/listTaskDone.html.twig', [
            'tasks' => $doctrine->getRepository(Task::class)->findBy(['isDone' => true])
        ]);
    }

    /**
     * @Route("/tasks/create", name="task_create")
     */
    public function create(Request $request): RedirectResponse|Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($task);
            $this->entityManager->flush();

            $this->addFlash('success', 'La tâche a été bien été ajoutée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/create.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/tasks/{id}/edit", name="task_edit")
     */
    public function edit(Task $task, Request $request): RedirectResponse|Response
    {
        $this->denyAccessUnlessGranted('TASK_EDIT', $task);
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();
            $this->addFlash('success', 'La tâche a bien été modifiée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/edit.html.twig', [
            'form' => $form->createView(),
            'task' => $task,
        ]);
    }

    /**
     * @Route("/tasks/{id}/toggle/done", name="task_toggle_done")
     */
    public function toggleDone(Task $task, ToggleTaskService $toggleTaskService): RedirectResponse
    {
        $this->denyAccessUnlessGranted('TASK_EDIT', $task);

        //set IsDone and return message
        $message = $toggleTaskService->toggleTask($task);

        $this->entityManager->flush();
        $this->addFlash('success', $message);
        return $this->redirectToRoute('task_list');
    }

    /**
     * @Route("/tasks/{id}/delete", name="task_delete")
     */
    public function deleteTask(Task $task): RedirectResponse
    {
        $this->denyAccessUnlessGranted('TASK_DELETE', $task);

        $this->entityManager->remove($task);
        $this->entityManager->flush();

        $this->addFlash('success', 'La tâche a bien été supprimée.');

        return $this->redirectToRoute('task_list');
    }
}

templates/task/_card.html.twig
<div class="card h-100">
    <div class="card-header">
        {% if task.isDone == false %}
            <span class="badge badge bg-secondary">Non fait</span>
        {% endif %}
        {% if task.isDone == true %}
            <span class="badge badge bg-success">Fait</span>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="card-title">
            <h4><a class="text-dark" href="{{ path('task_edit', {'id' : task.id }) }}">{{ task.title }}</a></h4>
        </div>
        <p class="card-text">{{ task.content }}</p>
        <small class="card-text text-muted">Edité par
            {% if task.user %}
                <i>{{ task.user.username }}</i>
            {% else %}
                <i>Anonyme</i>
            {% endif %}
        </small>
        <br>
        <small class="card-text text-muted">Crée le <i>{{ task.createdAt | date('d-m-Y') }}</i></small>
    </div>

    <div class="card-footer d-flex">
        <form action="{{ path('task_toggle_done', {'id' : task.id }) }}">
            {% if not task.isDone %}
                <button class="btn btn-success btn-sm pull-right me-2">Fait</button>
            {% else %}
                <button class="btn btn-secondary btn-sm pull-right me-2">Non fait</button>
            {% endif %}
        </form>
        <form action="{{ path('task_delete', {'id' : task.id }) }}">
            <button class="btn btn-danger btn-sm pull-right me-2">Effacer</button>
        </form>
    </div>
</div>

templates/task/_filter.html.twig
{{ form_start(form) }}
{{ form_rest(form) }}
<button type="submit" class="btn btn-primary">Filtrer</button>
{{ form_end(form) }}

templates/task/create.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block header_title %}
    <h1 class="text-center">Créer une tâche</h1>
{% endblock %}

{% block body %}
    <div>
        {{ form_start(form, {'action' : path('task_create')}) }}
            {{ form_widget(form) }}

            <button type="submit" class="btn btn-success pull-right">Ajouter</button>
        {{ form_end(form) }}

        <a href="{{ path('task_list') }}" class="btn btn-primary my-4">Retour à la liste des tâches</a>
    </div>
{% endblock %}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        {{ form_start(form, {'action' : path('task_edit', { 'id' : task.id })}) }}
            {{ form_widget(form) }}

            <button type="submit" class="btn btn-success pull-right">Modifier</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/task/list.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}<img class="slide-image" src="{{ asset('img/todolist_content.jpg') }}"
                           alt="todo list"><h1 class="text-center">Liste des tâches</h1>{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div id="message" class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    <div class="text-center mb-3">
        <a href="{{ path('task_create') }}" class="btn btn-info">Créer une tâche</a>
    </div>

    <div class="row">
        <div class="col-md-2">
            <h5 class="mb-3">Filtre :</h5>
            {% include 'task/_filter.html.twig' %}
        </div>
        <div class="col-md-10">
            <div class="grid">
                {% for task in tasks %}
                        {% include 'task/_card.html.twig' %}
                {% else %}
                    <div class="alert alert-warning " role="alert">
                        Il n'y a pas encore de tâche enregistrée. <a href="{{ path('task_create') }}"
                                                                     class="btn btn-warning pull-right">Créer une tâche</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/task/listTaskDone.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}<img class="slide-image" src="{{ asset('img/todolist_content.jpg') }}"
                           alt="todo list"><h1 class="text-center">Liste des tâches terminées</h1>{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div id="message" class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    <div class="text-center mb-3">
        <a href="{{ path('task_create') }}" class="btn btn-info">Créer une tâche</a>
    </div>

    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <div class="grid">
                {% for task in tasks %}
                        {% include 'task/_card.html.twig' %}
                {% else %}
                    <div class="alert alert-warning" role="alert">
                        Il n'y a pas encore de tâche enregistrée. <a href="{{ path('task_create') }}"
                                                                     class="btn btn-warning pull-right">Créer une tâche</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}